name: pass_app
description: A full-stack application to show Apple PassKit functionality.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  api_client:
    path: packages/api_client
  api_models:
    path: packages/api_models
  apple_passkit: ^1.3.1
  bloc: ^9.2.0
  csslib: ^1.0.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  intl: ^0.20.0
  meta: ^1.15.0
  pass_repository:
    path: packages/pass_repository
  passkit: ^1.1.0
  passkit_ui: ^1.0.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
